version: "3.7"
services:
  db:
    env_file:
      - .env.ci
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always

  api:
    env_file:
      - .env.ci
    expose:
      - "8001"
    volumes:
      - ./logs:/app/logs
      - static_files:/app/staticfiles/
    restart: always

  nginx:
    depends_on:
      - api
    image: nginx:1.19
    volumes:
      - ./deployment/nginx:/etc/nginx/conf.d
      - static_files:/www/static/
    ports:
      - "80:80"
    restart: always

volumes:
  static_files:
