version: "3.7"
services:
  db:
    image: postgres:13.1
    env_file:
      - .env.prod
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    expose:
      - "5432"

  api:
    image: astridyu/astrid_tech_api:latest
    depends_on:
      - db
    command: >
      bash -c "
        python3 manage.py collectstatic --noinput &&
        python3 manage.py migrate --database default &&
        gunicorn astrid_tech.wsgi:application --bind 0.0.0.0:8001
      "
    env_file:
      - .env.prod
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    expose:
      - "8001"
    volumes:
      - ./logs:/app/logs
      - static_files:/app/staticfiles/
    restart: always

  nginx:
    depends_on:
      - api
    image: nginx:1.19
    volumes:
      - ./deployment/nginx:/etc/nginx/conf.d
      - static_files:/www/static/
    ports:
      - "80:80"
    restart: always

volumes:
  static_files:
