version: "3.7"
services:
  db:
    image: postgres:13.1
    env_file:
      - .env.prod
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    expose:
      - "5432"

  api:
    image: astridyu/astrid_tech_api:latest
    depends_on:
      - db
    command: >
      bash -c "
        python3 manage.py collectstatic --noinput &&
        python3 manage.py migrate --database default &&
        gunicorn astrid_tech.wsgi:application --bind 0.0.0.0:8001
      "
    env_file:
      - .env.prod
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    expose:
      - "8001"
    volumes:
      - ./logs:/app/logs
      - static_files:/app/staticfiles/
    restart: always

  nginx:
    depends_on:
      - api
    image: staticfloat/nginx-certbot:latest
    volumes:
      - ./deployment/nginx:/etc/nginx/conf.d:ro
      - static_files:/www/static/
    environment:
      CERTBOT_EMAIL: astrid@astrid.tech
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt

volumes:
  letsencrypt:
  static_files:
