[package]
name = "astrid_tech_cms"
version = "0.1.0"
authors = ["Astrid Yu <astrid@astrid.tech>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
comrak = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.14"
yaml-rust = "0.4.4"
