name: astrid-tech-cms
version: 0.1.0.0
github: "astralbijection/astrid.tech"
license: BSD3
author: "Astrid Yu"
maintainer: "astrid@astrid.tech"
copyright: "Astrid Yu"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
synopsis: A CMS for somewhat-static sites
category: Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/astralbijection/astrid.tech#readme>

dependencies:
  - base >= 4.7 && < 5
  - servant
  - frontmatter
  - aeson
  - time

library:
  source-dirs: src

default-extensions:
  - DeriveGeneric
  - OverloadedStrings

executables:
  astrid-tech-cms-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - astrid-tech-cms

tests:
  astrid-tech-cms-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - astrid-tech-cms
