name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Import private key
        uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{secrets.PRIVATE_KEY}}

      - name: Set Git credentials
        run: git config --global user.email "astrid@astrid.tech" && git config --global user.name "Astrid A. Yu"

      - name: Yarn install
        uses: bahmutov/npm-install@v1.1.0

      - name: Build
        run: npm run build

      - name: Publish
        run: npm run deploy
