name: Build and Deploy

on:
  push:
    branches:
  workflow_dispatch: {}

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Install requirements
        working-directory: astrid_tech_api
        run: pip install -r requirements.txt

      - name: Run tests
        working-directory: astrid_tech_api
        run: ./manage.py test
        env:
          PYTHONUNBUFFERED: 1
          DJANGO_SETTINGS_MODULE: astrid_tech.settings.dev

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Import private key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{secrets.PRIVATE_KEY}}

      - name: Set Git credentials
        run: git config --global user.email "astrid@astrid.tech" && git config --global user.name "Astrid A. Yu"

      - name: Get yarn cache directory path
        working-directory: astrid_tech_frontend
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Fetch yarn caches
        uses: actions/cache@v2
        working-directory: astrid_tech_frontend
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Yarn install
        working-directory: astrid_tech_frontend
        run: yarn install

      - name: Build
        working-directory: astrid_tech_frontend
        run: npm run build

      - name: Publish
        working-directory: astrid_tech_frontend
        if: github.ref == 'refs/heads/main'
        run: npm run deploy
