name: Verify dev branch

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Yarn install
        uses: bahmutov/npm-install@v1.1.0

      - name: Ensure successfully builds
        run: npm run build
