[package]
name = "at_shortener"
version = "0.1.0"
authors = ["Astrid Yu <astrid@astrid.tech>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
dotenv = "0.15.0"
newbase60 = "0.1.0"
reqwest = "0.11.2"
scraper = "0.12.0"

[dev-dependencies]
rstest = "0.7.0"
